//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBPages.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WEBPages.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ctl00_PageContent_btnAuthenticate.
        /// </summary>
        internal static string CssBtnAuthSelector {
            get {
                return ResourceManager.GetString("CssBtnAuthSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ctl00_PageContent_txtPassword.
        /// </summary>
        internal static string CssPasswordSelector {
            get {
                return ResourceManager.GetString("CssPasswordSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ctl00_PageContent_txtUserName.
        /// </summary>
        internal static string CssUserNameSelector {
            get {
                return ResourceManager.GetString("CssUserNameSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[text()=&apos;My Performance Center&apos;].
        /// </summary>
        internal static string MyPCLink {
            get {
                return ResourceManager.GetString("MyPCLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;ctl00_PageContent_ddlDomains_DropDown&apos;]//li[contains(text(), &apos;.
        /// </summary>
        internal static string xPathDomainsDropDownList {
            get {
                return ResourceManager.GetString("xPathDomainsDropDownList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;ctl00_PageContent_ddlDomains_Input&apos;].
        /// </summary>
        internal static string xPathDomainSelector {
            get {
                return ResourceManager.GetString("xPathDomainSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;ctl00_PageContent_btnLogin&apos;].
        /// </summary>
        internal static string xPathLoginBtn {
            get {
                return ResourceManager.GetString("xPathLoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;MastheadDiv&apos;]/div[1]/div[2]/div[7].
        /// </summary>
        internal static string XPathLogoutBtn {
            get {
                return ResourceManager.GetString("XPathLogoutBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;ctl00_PageContent_ddlProjects_DropDown&apos;]//li[contains(text(), &apos;.
        /// </summary>
        internal static string xPathProjectsDropDownList {
            get {
                return ResourceManager.GetString("xPathProjectsDropDownList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;ctl00_PageContent_ddlProjects_Input&apos;].
        /// </summary>
        internal static string xPathProjectSelector {
            get {
                return ResourceManager.GetString("xPathProjectSelector", resourceCulture);
            }
        }
    }
}
